### ISSUE TITLE
Multiple excluding commands

### ISSUE THREAD

**Issue by gbrusella** [fschwiet/ManyConsole#22]
I was wondering if there is an option to create multiple excluding, like incompatible commands like

>console.exe -ACommand value1 -AnotherCommand value2

and display an error like

ACommand and AnotherCommand are not compatible. You should choose one or the other.

Or a way to check in the ACommand class and/or the AnotherCommand class if the other was already executed.

**Comment by fschwiet** [comment]
For custom validation, I'd suggest overriding OverrideAfterHandlingArgumentsBeforeRun.  Check the parameters that have been set, and if validation fails, throw a ConsoleHelpAsException with message for the user.

Your particular example "-ACommand" vs "-AnotherCommand" suggests that rather than do custom validation, you may want to have separate commands (by having a different class inherit from ConsoleCommand for each command).
