### ISSUE TITLE
No good way of handling boolean switches.

### ISSUE THREAD

**Issue by rovinbhandari** [fschwiet/ManyConsole#25]
If I just use the following in the code (taken from the example in this repo, as a matter of fact):

    this.HasOption("b|booleanOption", "Boolean flag option", b => BooleanOption = true);

then, at the command line, one cannot specify just `-b` because it complains of a missing value. And one can specify `-b true` or `-b false` or `-b maybe` and it would behave the same!

**Comment by fschwiet** [comment]
Weird.  I see you've taken the your example from the ExampleCommand, and it used to work appropriately (not requiring the missing value).  I don't know what has changed but I will look a bit further.

**Comment by fschwiet** [comment]
Oh.  For ExampleCommand in the Sample  project, it was complaining about missing values because it also has:
            HasAdditionalArguments(2, "<Argument1> <Argument2>");

Is that what you ran into for the example command?

  A weakness of the design is its easy to make the mistake of including a '=' in the spec:

            this.HasOption("b|booleanOption=", "Boolean flag option", b => BooleanOption = true);

  This will also cause the problem you saw.  So if you ran into the problem in another context, watch out for that.

**Comment by rovinbhandari** [comment]
I ran into the latter issue (with '='). Subtle difference! Closing the issue. :)
